driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
  - name: debian-7
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[build-essential]
  - recipe[ark]
  - recipe[ark_spec]
  attributes: {}
